language: rust
rust:
  - nightly
matrix:
  include:
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=i686-pc-windows-gnu
      os: windows
    - env: TARGET=i686-pc-windows-msvc
      os: windows
    - env: TARGET=i686-unknown-linux-gnu
      dist: bionic
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-pc-windows-gnu
      os: windows
    - env: TARGET=x86_64-pc-windows-msvc
      os: windows
    - env: TARGET=x86_64-unknown-linux-gnu
      dist: bionic