language: rust

rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: stable
  fast_finish: true

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - ppc64le
  - s390x
  - arm64

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --verbose --release
  - cargo test --verbose --release