[package]
name = "array-tools"
version = "0.2.3"
authors = ["Mikhail \"L117\" Nikolenko <l117@l117.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
